Upgrade service to bal 7
wso2/open-healthcare-prebuilt-services pull request #29
Opened 2023-09-14 09:30 UTC by ThishaniLucas

2023-09-14 13:55 UTC, nirmal070125 requested changes

2023-09-14 13:55 UTC, nirmal070125 commented on service.bal
> +service http:InterceptableService / on new http:Listener(9090) {
@ThishaniLucas why do we need this?

2023-09-15 04:17 UTC, nirmal070125 approved these changes

2023-10-10 07:39 UTC, ThishaniLucas commented
Closing since the changes are added with https://github.com/wso2/open-healthcare-prebuilt-services/pull/31

2023-10-10 07:39 UTC, closed without merging